# This will run on Travis' 'new' container-based infrastructure
sudo: required
dist: trusty
language: c++

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: Machine-Learning-Toolkit
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doc/Doxyfile
    - GH_REPO_REF: https://github.com/mateus558/Machine-Learning-Toolkit.git

# Install dependencies
addons:
  apt:
  	sources:
  	  - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
env: COMPILER=g++-5
# Build your code e.g. by calling make
script:
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
