# This will run on Travis' 'new' container-based infrastructure
sudo: false


# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: Machine-Learning-Toolkit	
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doc/Doxyfile
    - GH_REPO_REF: https://github.com/mateus558/Machine-Learning-Toolkit.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      
before_install: sudo apt-get update -qq
# Build your code e.g. by calling make
script:
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh


