all:
	g++ -g --std=c++11 -W data.cpp sample.cpp embrapa.cpp utils.cpp kernel.cpp imap.cpp imadual.cpp perceptron.cpp adaboost.cpp adaboostdual.cpp almap.cpp smo.cpp golub.cpp fisher.cpp rfe.cpp main.cpp -o fs 

