#ifndef VALIDATION__HPP
#define VALIDATION__HPP

#include "Classifier.hpp"
#include "Data.hpp"
#include "ValidationSolution.hpp"

/**
 * \brief Class of methods for the validation of ML algorithms.
 */
class Validation {
    // Attributes
    private :
        Classifier classifier;
        Data train_sample;
        Data test_sample;
        double initial_error;
        double limit_error;
        double actual_error;
        /// Solution generated by the validation.
        /// 
        ValidationSolution solution;
    // Operations
    public :
        CrossValidation (Data sample, Classifier classifier);
        double kFold (int fold, int seed);
        void validation (int fold, int qtde);
        Data getTestSample ();
        Data getTrainSample ();
};

#endif
