#ifndef VALIDATIONSOLUTION__HPP
#define VALIDATIONSOLUTION__HPP

#include "Solution.hpp"

/**
 * \brief Solution for the validation of a ML method.
 */
class ValidationSolution : public Solution {
    // Attributes
private :
    /// Accuracy of the validated model.
    double accuracy = 0;
    /// Number of false positives generated by the classifier in the evaluation.
    int falsePositive = 0;
    /// Number of false negatives generated by the classifier in the evaluation.
    int falseNegative = 0;
};

#endif
